### ISSUE TITLE
warning  deapricated componentWillReceiveProps and componentWillUpdate

### ISSUE THREAD

**Issue by fereshtehaboohamzeh** [reactjs/react-redux#923] opened 2018-04-08 05:42 UTC
warning in react-native v54 and react-redux v5.0.6

**Comment by markerikson** [comment] 2018-04-08 15:44
Duplicate of #915 - please upgrade to 5.0.7 to fix this.

**Closed by markerikson** 2018-04-08 15:44 UTC

**Comment by gaearon** [comment] 2018-04-08 15:51
I don’t think it’s related. This is probably about https://github.com/facebook/react-native/issues/18175#comment-379253428.

React Native 0.55.2 will fix this b

**Comment by markerikson** [comment] 2018-04-08 15:53
Ah, okay.  Good to know.
