### ISSUE TITLE
Impure connected component aren't updated when the store changes state

### ISSUE THREAD

**Issue by andydavies92** [reactjs/react-redux#428] opened 2016-07-06 10:38 UTC
From the [docs](https://github.com/reactjs/react-redux/blob/master/docs/api.md#arguments):

> \[`pure = true`\] _(Boolean)_: If true, implements `shouldComponentUpdate` and shallowly compares the result of `mergeProps`, preventing unnecessary updates, assuming that the component is a “pure” component and does not rely on any input or state other than its props and the selected Redux store’s state. _Defaults to `true`_.

Given this, I would expect impure components to _always_ be re-rendered whenever the store changes, as it cannot assume that some variable it depends on outside its props or the store hasn't been mutated. However, this does not seem to be the case as [this fiddle](https://jsfiddle.net/andydavies92/ox3ktvjc/) demonstrates:

```javascript
const store = Redux.createStore(() => ({}));
let impureDependency = "Initial value";

class MyComponent extends React.Component {
    render() {
        return <div>{ impureDependency }</div>;
    }
}

const connect = ReactRedux.connect(() => ({}), null, null, { pure: false });
const MyConnectedComponent = connect(MyComponent);

ReactDOM.render(
    <ReactRedux.Provider store={store}>
        <MyConnectedComponent />
    </ReactRedux.Provider>,
    document.getElementById("container")
);

impureDependency = "Updated value";
store.dispatch({ type: "ACTION" });
```

The render method for `MyComponent` is dependent on variable `impureDependency` outside both its props and the Redux store, making it an impure component, and a connected version of the component, `MyConnectedComponent`, is subsequently created on line 11. This variable has its value changed from `"Initial value"` to `"Updated value"` on line 20. A dummy action is dispatched to the store on line 21 (causing the store state to change as store reducers will _always_ return a new state), at which point we'd expect `MyConnectedComponent` to be re-rendered but the rendered text remains as `"Initial value"`.

This is due to `Connect.prototype.render()` failing to check if a component is pure before determining whether re-rendering the component can be skipped or not. The solution is to add this check so that impure components always get re-rendered.

**Comment by andydavies92** [comment] 2016-07-06 10:40
Submitted pull request #429 to fix this issue

**Comment by jimbolla** [comment] 2016-07-06 10:45
#416 probably already fixes this

**Comment by andydavies92** [comment] 2016-07-06 11:02
> #416 probably already fixes this

@jimbolla, please could you verify by running the new test I added in #429?

**Comment by jimbolla** [comment] 2016-07-06 11:37
Probably = 99% sure. 416 should land as a beta very soon. Dan said he'd do it, so whenever it's top priority.

**Comment by andydavies92** [comment] 2016-07-06 11:50
Still makes sense to me to fix the current implementation in the short-term even if it ends up getting replaced in a month or so when the next major is released. Plus, the test introduced in #429 is a worthwhile addition to make sure #416 or any future work doesn't create a regression. I guess it's up to @gaearon as to whether #429 is worth merging or not...

**Comment by jimbolla** [comment] 2016-07-06 11:58
Yeah the test sounds valuable. I'll try to pull it into my fork. I'm hoping the beta release happens sometime this week, but I can't say when it might make it to production

**Comment by gelguy** [comment] 2016-07-06 23:35
The root of the problem actually lies in `this.haveOwnPropsChanged` not being set correctly.

``` javascript
      componentWillReceiveProps(nextProps) {
        if (!pure || !shallowEqual(nextProps, this.props)) {
          this.haveOwnPropsChanged = true
        }
      }
```
From [https://github.com/reactjs/react-redux/blob/master/src/components/connect.js#L215](https://github.com/reactjs/react-redux/blob/master/src/components/connect.js#L215)

In this scenario, we want to update the component using a dispatch to the store. This is a state change, hence `componentWillReceiveProps` is not called. This does not set the `haveOwnPropsChanged` field to `true` (which it should for an impure component), so in `render()` the optimised route is taken.

#429 fixes the current problem, but does not fix the root of it, which is that the impure component needs to update on store change (which is a state change), so `componentWillUpdate` is required together with `componentWillReceiveProps`. We can test this by using

```      @connect(() => ({}), null, () => {invocationCount++; return {}}, { pure: false }) ```

and seeing that invocationCount does not increase with the current fix.

However, since `componentWillUpdate` is called after `shouldComponentUpdate` as opposed to `componentWillReceiveProps`, and that hot-loading overrides `componentWillUpdate` in the prototype, there might be a better alternative solution.

#416 should ultimately fix this as it uses `shouldComponentUpdate` to do all the checks.

**Comment by DouglasLivingstone** [comment] 2016-07-08 11:03
> #416 should ultimately fix this as it uses shouldComponentUpdate to do all the checks.

Yes, I've tested #416 and it does fix this too.

> seeing that `invocationCount` does not increase with the current fix.

Since merging props is always shallow, the shallow equality checks are sufficient to control whether a merge needs to happen or not. It is just that for impure objects, a shallow equality check isn't sufficient to tell whether the wrapped component should re-render.

> is this the expected behaviour?

I'd say yes, impure components should always return true from `shouldComponentUpdate`, since the props from the parent and the props from the store may have changed in a way that requires an update, even if they still match with a shallow equality comparison.

The docs say that the test for pure components is against `mergedProps` rather than against either `ownProps` or the props from the store, so the fix in #429 to have impure components ignore `haveMergedPropsChanged` seems correct.

**Comment by gelguy** [comment] 2016-07-08 18:21
> Since merging props is always shallow, the shallow equality checks are sufficient to control whether a merge needs to happen or not

This is mostly true. One case I can think of is if `mergeProps` is not pure, which is what the `invocationCount` test checks.

> impure components should always return true from shouldComponentUpdate

This occurs currently. The bug lies in that `this.haveOwnPropsChanged` is not updated correctly as setting state does not trigger `componentWillReceiveProps`.

I apologise if I did not make my question clear, but the issue with #429 was that with any Redux store update, all impure components will re-render. Should this be the case? A wrapped component will update when the props passed to it by the parent changes, or if the Redux store updates. For pure components, check is then done by merging the store state and props to see if re-rendering is needed. For impure components, if props have the parent have changed, then it should cause a re-render. If the store has changed, we have two scenarios. The impure component always updates if the store has updated, or it updates if the slice of store it is interested in (via `mapStateToProps`) changes. #429 assumes the first scenario, but I feel otherwise, since the component is then re-rendering on every update on the store.

There are ways to overcome the impure component not re-rendering, e.g. by calling the component's `setState` or `forceUpdate` from outside Redux. I am not too familiar with using Redux with impure components, so I think clarifying the expected behaviors will be useful in the future.

**Comment by DouglasLivingstone** [comment] 2016-07-08 21:50
Agreed, merging either of these patches would be a change in behaviour to re-render the component whenever the store updates, it is just by chance that we ran into this around the same time that #429 was proposed.

Currently we're using impure components while we migrate our existing Flux-like stores to Redux, since the logic for pure components can't see inside our non-Redux stores. I mistakenly thought that using the impure option would move the burden for implementing `shouldComponentUpdate` (or an element caching alternative) from the connection wrapper component to the wrapped component, and was surprised that it no-longer updated.

We ran into this while trying to consolidate the re-render after store update to only happen once both our Redux and non-Redux stores had updated, by only rendering via the impure component's subscription to the Redux store. When an action updates only one of our non-Redux stores, only the top level object in our Redux store changes. So another option for us would be to have our impure components subscribe to the entire Redux store state, then just ignore the new value.

Since there are so many workarounds, it is a question of what the default case should be rather than how to make it work for us.

There is some elegance is saying that the wrapper controls when to re-render pure components, while the wrapped component controls when to re-render if it is impure.

**Closed** 2016-08-14 15:16 UTC
