### ISSUE TITLE
4.4.8 throws PropTypes validation warnings for React 14

### ISSUE THREAD

**Issue by scottarivale** [reactjs/react-redux#669] opened 2017-04-12 00:10 UTC
For every component we use 'connect' in, we get the following JS warning on every render:
```
Warning: Failed Context Types: Calling PropTypes validators directly is not supported by the `prop-types` package. Use `PropTypes.checkPropTypes()` to call them. Read more at http://fb.me/use-check-prop-types Check the render method of `[NAME OF COMPONENT]`
```

Right now, each page load brings about 2000 of these warnings.

For example, using the following component throws warnings:
```
import React, { Component } from 'react'
import { connect } from 'react-redux'

class FeedCard extends Component {
  render() {
   return <div />
  }
}

export default connect(null, {
  updateFeedItem,
})(FeedCard)
```

But simply removing the 'connect' usage "fixes" the problem (although it renders the component useless):
```
import React, { Component } from 'react'
import { connect } from 'react-redux'

class FeedCard extends Component {
  render() {
   return <div />
  }
}

export default FeedCard
```

I confirmed that downgrading to 4.4.7 makes the issue go away.
We are using React 0.14.8

**Comment by timdorr** [comment] 2017-04-12 00:14
@gaearon So, is `prop-types` not compatible with 0.14 then? 😄

**Comment by kulakowka** [comment] 2017-04-12 12:23
I have this problem too. 
React 0.14.8 and react-redux 4.4.8.

**Comment by gaearon** [comment] 2017-04-12 14:01
Okay, this one is hard.. Let me think on it.

**Comment by gaearon** [comment] 2017-04-12 14:06
The problem is technically those warnings were introduced in React 15. And `prop-types` was extracted from React 15. So by migrating the library to use them you’re kind of opting into seeing those warnings.

But in this case they’re not actionable because they’re coming from React itself. 😞

**Comment by gaearon** [comment] 2017-04-12 15:03
I'm going to try to cut `prop-types`-compatible 0.14.9 which is the real fix here.

**Comment by gaearon** [comment] 2017-04-12 15:50
Okay, `react@0.14.9` and `react-dom@0.14.9` are out, and they should play nice with `prop-types`. Other React-related packages were not updated. Let me know if it helps.

**Comment by gaearon** [comment] 2017-04-12 16:11
I also cut `prop-types@15.5.8` which only prints the warning 3 times at most (so that even a false positive with `react` < `0.14.9` is less annoying).

**Comment by timdorr** [comment] 2017-04-12 17:49
![](https://i.giphy.com/RRerwvHrb0nxm.gif)
Look at Dan go!

Looks like the issue is upstream with React itself, so I'm closing this one out.

**Closed by timdorr** 2017-04-12 17:49 UTC
