### ISSUE TITLE
Investigate when a context from another library causes us to opt out of perf optimizations

### ISSUE THREAD

**Issue by gaearon** [reactjs/react-redux#366] opened 2016-04-22 20:21 UTC
Related to #99 and the follow-up issues and pull requests.
I’d like to understand better in which cases we have the behavior described in https://github.com/reactjs/react-redux/issues/365#issuecomment-213575855:

>I dug into why this happens, and it seems like [returning a cached element in `render()`](https://github.com/reactjs/react-redux/blob/253ce8b3068d9d9bfe55f70a6f18a5fde313b326/src/components/connect.js#L324-L326) is not enough to prevent a re-render in some cases when there is an additional context between `<Provider>` and the `connect()`ed component [because of this check in `ReactReconciler`](https://github.com/facebook/react/blob/5ddfee8cfece399d686862f2ac2796b63eb78f00/src/renderers/shared/reconciler/ReactReconciler.js#L98).

Is just having another component providing context enough to trigger this? Is there any way we can work around this?

**Comment by foiseworth** [comment] 2016-07-05 11:06
I did some investigating into this and the issue seems to be caused by the following:
1. There is a component with getChildContext above the connected component (one will usually be Provider).
2. The cached element has getChildContext
2. React merges the contexts in _processChildContext by assigning to an empty object thus creating a new context object
3. New context object fails equality check thus stopping early bail out in ReactReconciler

Not sure how you can work around this. Changing the equality check in ReactReconciler to a shallowEquals check would work.

**Comment by markerikson** [comment] 2016-07-05 15:36
Thanks for looking into this!  Does the rewrite in #416 happen to eliminate this issue?

**Comment by jimbolla** [comment] 2016-07-05 16:07
416 doesn't cache the element, only the final props, since more aggressive shouldComponentUpdate() means render will only fire if it actually needs to rerender, so I would guess it does.?

**Comment by foiseworth** [comment] 2016-07-05 17:28
Did some testing and and 416 fixes the issue and it does indeed seem to be down to shouldComponentUpdate. Some unscientific testing shows a massive perf increase as well.

**Comment by DouglasLivingstone** [comment] 2016-07-08 12:31
A similar situation is when the `Provider` itself gets re-rendered, as in:

    service.onUpdate(() => ReactDOM.render(<Provider>....</Provider>, element))

This causes the context from `Provider` to be re-generated, so `context === internalInstance._context` fails. I'd guess that #416 fixes this too.

**Comment by foiseworth** [comment] 2016-08-09 15:48
I did some further testing can confirm that this can be quite an issue if you're using context:

**What you would expect**
1. connect a component
2. change the store state
3. it re-renders and either it or something in between it and the next component has getChildContext
4. somewhere down the tree  a connected sub component is rendered
5. the sub component connect's shouldComponentUpdate will return true (because store state has changed)
6. the sub component connect's render method returns the cached element (because its calculated props haven't changed)
7. React uses cached element, perf win!

**What happens**
1. connect a component
2. change the store state
3. it re-renders and either it or something in between it and the next component has getChildContext
5. the return of getChildContext is merged with the previous getChildContext into an empty object
6. somewhere down the tree  a connected sub component is rendered
7. the sub component connect's shouldComponentUpdate will return true (because store state has changed)
8. the sub component connect's render method returns the cached element (because its calculated props haven't changed)
9. React detects that context is a different object and discards cached element
10. Element (and therefore tree) is re-rendered 

To combat it, in the short term I'm going to try to move all my getChildContext above my connected components.

In the long term I guess:
- we advise people to avoid using context with react-redux
- we switch to another method (should as shouldComponentUpdate) for not re-rendering child such as in https://github.com/reactjs/react-redux/pull/416
- we think about the behaviour of React and submit an PR to change it (I'm still thinking it should be a shallow compare rather than an equality check on context in React Reconciler).

**Comment by foiseworth** [comment] 2016-08-11 07:12
One great example of the causing the above bug is if you wrap your top level component in connect. As it will wrap the Provider component which has getChildContext, anytime it re-renders (due to a store update which leads to a change in the output of mapStateToProps) the entire tree will re-render unless you have some non-connect shouldComponentUpdate logic.

**Closed** 2016-08-14 15:15 UTC
Labels: enhancement, help wanted
