### ISSUE TITLE
I keep seeing 'Provider does not support changing store...' error

### ISSUE THREAD

**Issue by yasserhussain1110** [reactjs/react-redux#854] opened 2018-01-11 09:35 UTC
This is the repo I am reporting this error about https://github.com/yasserhussain1110/sona-sarovar-trust

I am using react hot loader. I start the app and try to update a `React Component` by adding a new **state** field in the constructor. I see this error. 

> <Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions

I have followed the instructions to enable redux hot reloading. What could be going wrong?

**Comment by timdorr** [comment] 2018-01-11 14:56
Duplicate of #809

**Closed by timdorr** 2018-01-11 14:56 UTC
