### ISSUE TITLE
defaultMergeProps and checkMergedEquals issue

### ISSUE THREAD

**Issue by Andarist** [reactjs/react-redux#381] opened 2016-05-16 11:30 UTC
Hey,
I think I've found a bug, but I might be missing something here, so an explanation would be greatly appreciated in case I'm wrong. :) Let me describe the issue:

1. Not supplying custom `mergeProps` is defaulting it to `defaultMergeProps` (obviously ;) )
2. and therefore we land with `checkMergedEquals === false` ( cause `const checkMergedEquals = pure && finalMergeProps !== defaultMergeProps` )
3. then each call to `this.updateMergedPropsIfNeeded` returns as always `true` as if `mergedProps` has changed (which is not always true!) - if we are using `defaultMergeProps` they can not change too 
4. and finally... it is a problem in `render` as it won't return us cached `renderedElement` due to:

```
if (!haveMergedPropsChanged && renderedElement) {
    return renderedElement
}
```

It successfully prevents default optimization here.

**Comment by gaearon** [comment] 2016-05-16 11:39
Please feel free to provide a failing test and a solution!

**Comment by Andarist** [comment] 2016-05-16 11:41
I can make a PR with a fix, would only like to hear if my reasoning is not wrong, cause I could have miss something. And probably what cases should I consider when fixing - as probably whole `checkMergedEquals` had some reason behind implementing it :) 

Gonna read commit history later, maybe that will help

**Comment by gaearon** [comment] 2016-05-16 14:59
I don’t remember that so creating a failing test is the best way to figure out if there was a reason or not

**Comment by gelguy** [comment] 2016-05-20 23:45
I think this is working as intended.

The variable `checkMergedEquals` indicates whether or not we need to do the `shallowEqual` comparison on the old mergedProps and next mergedProps.

```js
        if (
          haveStatePropsChanged ||
          haveDispatchPropsChanged ||
          haveOwnPropsChanged
        ) {
          haveMergedPropsChanged = this.updateMergedPropsIfNeeded()
        } else {
          haveMergedPropsChanged = false
        }
```
The condition to reach `updateMergedPropsIfNeeded` is if stateProps, dispatchProps or ownProps has changed. This implies that at least one of these are not shallowEqual to its previous counterpart.  Therefore if we use the default `mergeProps`, we know for sure the new mergedProps will not be shallowEqual the old mergedProps, allowing us to bypass the `shallowEqual` check entirely.

The shallowEqual check on mergedProps only needs to be done if we have a custom `mergeProps` (e.g. trivial example one that always returns the empty object) and the component is pure (since if it is impure we want to trigger a re-render).

**Comment by gaearon** [comment] 2016-06-26 18:30
Closing per inactivity, doesn’t seem like there is any actionable here.

**Closed by gaearon** 2016-06-26 18:30 UTC
