### ISSUE TITLE
Pass own props to `areStatesEqual`

### ISSUE THREAD

**Issue by gawhyte** [reactjs/react-redux#907] opened 2018-03-26 18:28 UTC
I have often found myself wishing that a component's own props were available in the `areStatesEqual` method. I usually use an [immutable.js](https://github.com/facebook/immutable-js) store and convert to plain JS objects while mapping (which can potentially be expensive) and use `areStatesEqual` to prevent mapping unnecessarily. I am also sometimes using a property of the component to slice off a subsection of the state which leads me to wish I could sometimes do something like this:

```
connect(
    (state, props) => state[props.context].toJS(),
    null,
    null,
    {
      areStatesEqual: (nextState, prevState, nextProps, prevProps) => nextState[nextProps.context].equals(prevState[prevProps.context]),
    }
)
```

Does anybody else encounter/wish for this? Is there a philosophical reason this shouldn't be done? Looking at the code it appears it would be trivial to make this change. I thought it best I should check before opening a pull request.

**Comment by timdorr** [comment] 2018-03-26 18:35
Dupe of #781

**Closed by timdorr** 2018-03-26 18:35 UTC
