### ISSUE TITLE
mapDispatchToProps not re-invoked when ownProps change

### ISSUE THREAD

**Issue by jaschaio** [reactjs/react-redux#810] opened 2017-10-20 09:14 UTC
From the documentation:

> If your `mapDispatchToProps` function is declared as taking two parameters, it will be called with dispatch as the first parameter and the props passed to the connected component as the second parameter, **and will be re-invoked whenever the connected component receives new props.**

Unfortuantely this is not working for me. Within the `mapStateToProps` it does work, but the `mapDispatchToProps` function is not re-invoked when the connected component props are changed. As the documentation states that as the normal behaviour, what am I doing wrong?

**Comment by markerikson** [comment] 2017-10-20 17:52
Can you provide a minimal repro example that demonstrates the behavior?  I'm pretty sure we implement the behavior for `mapState` and `mapDispatch` the same way internally, so I would expect both of those to behave the same way.

**Comment by jaschaio** [comment] 2017-10-20 19:19
Me too, thats why I found it so weird that it does work with mapState but not mapDispatch.

I have searched for a couple of hours for a solution but didn't managed to re-iniate the `mapDispatchToProps` function when Props change. The console.log of the `mapDispatchToProps` gets only invoked once on page load, the console.log of the `mapStateToProps` gets invoked each time the Props change (as intented).

`
import * as actionCreators from '../actions/actionCreators';

const mapStateToProps = (state, ownProps) => {
    console.log(ownProps);

    return {
        authenticate: state.authenticate,
        days: state.days,
        messages: state.messages,
        metas: state.metas,
        notices: state.notices
    };
};

const mapDispatchToProps = (dispatch, ownProps) => {
    console.log(ownProps);

    return bindActionCreators( actionCreators, dispatch );
}

export default connect(mapStateToProps, mapDispatchToProps)(Main);
`

I kind of feel that it has something to do with the logic that checks for `mapDispatchToProps.dependsOnOwnProps` inside [the `handleNewPropsAndNewState` method](https://github.com/reactjs/react-redux/blob/f892ec00d7e92ff7afb21498276472f0e3b000c5/src/connect/selectorFactory.js#L45), but I couldn't find out or understand how that flag is set. It should be set automatically if the component has properties, but as I said it doesn't work. Only the `mapDispatchToProps` function has this logic to it and the `mapStateToProps` doesn't so this would explain why it works with one but not with the other one.

**Comment by jaschaio** [comment] 2017-10-24 06:31
Here is a minimal repro that reproduces the unexpected behaviour of `mapDispatchToProps`. There is an event listener that dispatches an "INCREASE_CLICKS" action each time you click within the app. `mapStateToProps` gets re-invoked and logged to the console, `mapDispatchToProps` doesn't. Hope this helps to understand the problem and find a solution.

https://github.com/jaschaio/mapDispatchToProps

**Comment by viniciuslacerda** [comment] 2017-11-04 23:57
Looks like `ownProps` stores only the properties that are explicitly passed to the component that connect creates, and doesn't carry the props dynamically added by `mapStateToProps` and `mapDispatchToProps`.

As `store` is the only prop that's passed on [`index.js:16`](https://github.com/jaschaio/mapDispatchToProps/blob/master/src/index.js#L16) every time react-redux verifies if ownProps is still equals, it yields true.

`ownProps` is created used the `this.props` of the connect component when its instantiated, [here](https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L191).

So seems like intended behavior here.

**Comment by markerikson** [comment] 2017-11-05 00:03
@viniciuslacerda , @jaschaio : yes, `ownProps` is _only_ the props that were passed to the outer wrapper component generated by `connect`.  

Looking at the repro example, I see that the top-level render is `<Main store={store} />`.  In that example, `ownProps` will be `{store}`, which is definitely not going to change.

It seems like the issue here is not a bug, but rather understanding what exactly `ownProps` refers to, so I'll close this.  If you do have an example that demonstrates the actual `ownProps` changing and `mapDispatch` not re-running, please leave a comment and we can re-examine things.

**Closed by markerikson** 2017-11-05 00:03 UTC
